name: Build Android App with Dioxus

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        override: true

    - name: Install Android NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk-libsparse-utils android-sdk-platform-tools
        echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.4.7075529"

    - name: Install Dioxus CLI
      run: cargo install dioxus-cli

    - name: Bundle Android App
      run: |
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529
        dioxus bundle --target android

    # - name: Upload APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-debug
    #     path: target/dx/cdc/bundle/android/bundle/android/cdc.apk
