name: Build Android App with Dioxus

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup linux dev
      run: |
        sudo apt update
        sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          openssl

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        override: true

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.deb
        sudo dpkg -i jdk-23_linux-x64_bin.deb
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d $HOME/android-sdk-temp
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk-temp/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;28.0.13004108" "platform-tools"
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH:$HOME/android-sdk/ndk/28.0.13004108

    - name: Install Dioxus CLI
      run: cargo install dioxus-cli

    - name: Bundle Android App
      run: |
        export ANDROID_NDK_HOME=$HOME/android-sdk/ndk/28.0.13004108
        cargo clean
        dx bundle --platform android --no-default-features --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CDC
        path: /home/runner/work/cdc_dioxus/cdc_dioxus/target/dx/cdc/release/android/app/app/build/outputs/bundle/release/Cdc-aarch64.aab
